name: Placeholder

on:
  workflow_dispatch:

permissions: {}

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Placeholder workflow to provide a GitHub Actions source file for CodeQL analysis."
